# Numpy
---

### 세팅

Numpy 설치

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Numpy 불러오기

In [ ]:
import numpy as np

Numpy 버전 알기

In [ ]:
np.__version__

'1.22.4'

### 생성
> 대부분의 numpy 기능은 ndarray 객체를 만들어야 한다.

ndarray 만들기

In [ ]:
a = np.array([1,2,3])

마지막 란 객체는 자동 출력

In [ ]:
a

array([1, 2, 3])

객체를 프린트하면 형태가 다르다.

In [ ]:
print(a)

[1 2 3]


이차원 배열

In [ ]:
b = np.array([[1,2],[2,3],[4,5]])
b

array([[1, 2],
       [2, 3],
       [4, 5]])

3차원 배열

In [ ]:
c = np.array([[[1,2],[2,3],[4,5]]])
c

array([[[1, 2],
        [2, 3],
        [4, 5]]])

타입 알기

In [ ]:
type(c)

numpy.ndarray

a와 b를 여러 라인으로 보자

In [ ]:
print(a)
b

[1 2 3]


array([[1, 2],
       [2, 3],
       [4, 5]])

속성 알기
- shape :  데이터의 형태를 보여준다.
- 나열해놓으면 튜플 형태로 반환된다.
- 뒤의 콤마의 의미=> 안의 원소가 3개 있다.
> (1,3,2) : 제일 안에 있는 리스트가 원소가 2개짜리 -> 그 2개까지가 3개 모여있음 -> 그 3개짜리가 한개
=> 안(뒤)에서부터 생각하자.

In [ ]:
a.shape, b.shape, c.shape

((3,), (3, 2), (1, 3, 2))

데이터 타입 알기
- int64 -> 정수 하나를 표시하기 위해 64bit를 사용

In [ ]:
c.dtype

dtype('int64')

> numpy는 전체 하나의 타입으로만 가능하다.

하나라도 문자열이라면 정수 데이터가 문자열로 변환된다.

In [ ]:
a = np.array([1,'2',3])
a.dtype

dtype('<U21')

numpy은 다차원 데이터를 다루기 때문에 축이 존재한다.
- vector: 축이 하나 -> 0번째 축
- 2차원 -> row가 축 (2,3,) => 행이 2, 열이 3

0으로 채우기

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

1로 채우기

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

a와 똑같은 형태(차원을 가진)를 만들어 0으로 채우자

In [ ]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

0부터 9까지의 배열 만들기

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy 랜덤

정규분포

- 표준 정규분포 : 평균을 0으로 잡음

랜덤
1. uniform : 뽑을 때 확률이 동일
2. 정규분포(normal) : 10번을 뽑으면 중간 값들이 뽑일 확률이 높다.

(정규분포) 평균이 10이고 표준편차가 3인 데이터를 (2,3) shape으로 추출하자

In [ ]:
np.random.normal(10,3,(2,3))

array([[ 8.25861157, 12.34742781, 11.14404986],
       [12.6413804 ,  8.24976254,  9.58550386]])

(uniform) 0하고 1 사이의 (3,2) shape으로 추출하자

In [ ]:
np.random.rand(3,2)

array([[0.89848574, 0.15791151],
       [0.92610985, 0.66330313],
       [0.82268564, 0.14886121]])

(표준정규분포) 평균이 0이고 표준편차가 1인 (3,4) shape으로 추출하자.

In [ ]:
np.random.randn(3,4)

array([[ 0.03970067,  1.15767768, -0.36796478,  1.9482811 ],
       [ 1.95986807,  0.680644  , -1.53896224, -1.14943227],
       [-0.07497294,  0.44503167, -0.71108344,  1.27844094]])

0부터 11까지 배열 a

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

reshape

: 모델이 원하는 형태로 데이터를 가공하자

> numpy는 원래 원본이 바뀌지 않는다.

In [ ]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = a.reshape(2,3,2)
a.shape

(2, 3, 2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

(-1, 2, 2) : 데이터가 몇 개 있는지는 모르지만 최종적으로 (2,2)짜리 matrix가 여러개 있었으면 좋겠다.

In [ ]:
a = a.reshape(-1,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

### 연산

산술연산

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[2,3],[3,4]])
b

array([[2, 3],
       [3, 4]])

In [ ]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[2, 3],
        [3, 4]]))

In [ ]:
a + b, a-b, a*b, a/b

(array([[3, 5],
        [6, 8]]),
 array([[-1, -1],
        [ 0,  0]]),
 array([[ 2,  6],
        [ 9, 16]]),
 array([[0.5       , 0.66666667],
        [1.        , 1.        ]]))

행렬연산

In [ ]:
a @ b

array([[ 8, 11],
       [18, 25]])

In [ ]:
np.dot(a,b)

array([[ 8, 11],
       [18, 25]])

비교연산
- 같은 자리끼리 연산한다.

In [ ]:
a == b

array([[False, False],
       [ True,  True]])

In [ ]:
a > b

array([[False, False],
       [False, False]])

Broadcasting

:
두개가 모양이 같도록 변형한다.

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a + 3

array([[4, 5],
       [6, 7]])

In [ ]:
a + [3]

array([[4, 5],
       [6, 7]])

In [ ]:
a + [2,1]

array([[3, 3],
       [5, 5]])

양쪽을 더해도 형태가 통합되지 않는 경우가 있다.

In [ ]:
a = np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

a의 모든 값을 더해라

In [ ]:
np.sum(a)

66

a의 0번째 축을 더해라

In [ ]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [ ]:
a.sum(axis=0)

array([12, 15, 18, 21])

a의 1번째 축을 더해라

In [ ]:
np.sum(a, axis=1)

array([ 6, 22, 38])

a의 전체 평균을 구해라

In [ ]:
np.mean(a)
a.dtype

dtype('int64')

a의 0번째 축의 평균을 구해라

In [ ]:
b = np.mean(a, axis=0)
b.dtype

dtype('float64')

### 슬라이싱(인덱싱)
: 내가 필요한 데이터만 가져오자

인덱싱

: 하나만 가지고 옴

슬라이싱

: 범위 전체를 가지고 옴
1. Boolean
2.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[4]

4

1에서 4까지만 가져오자

In [ ]:
a[1:4]

array([1, 2, 3])

전체 다 가져오자

In [ ]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-1 : 제일 뒤를 의미

In [ ]:
a[-1]

9

In [ ]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[:-3:-1]

array([9, 8])

In [ ]:
a = np.arange(1,25).reshape(-1, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
a[1]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
a[1:3]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
a[0,1]

2

In [ ]:
a[0:3, 1:3]

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

Fancy indexing

In [ ]:
a[[0, 2], [0,1]]

array([ 1, 14])

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a[[0,3]]

array([1, 4])

Boolean indexing

In [ ]:
a[[True, False, True, False]]

array([1, 3])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5보다 큰 값만 가져온다.

In [ ]:
a[a > 5]

array([6, 7, 8, 9])

짝수만 뽑는다.

In [ ]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

다시 1차원배열로 올리자

In [ ]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = a.reshape(-1, 1)
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
a.shape

(12, 1)

In [ ]:
a = a.reshape(-1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.zeros_like(a)
b

array([[0, 0],
       [0, 0]])

결합을 하려면 shape이 비슷해야 한다.

두 개의 array 합치기

- 0번째 축으로 -> 아래에 붙임
- 1번째 축으로 -> 오른쪽에 붙임

In [ ]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[1, 2, 0, 0],
       [3, 4, 0, 0]])